project_id = "eqtzrftndyninwasclfd"

[functions.delete-account]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-digest-email]
verify_jwt = false

[functions.crypto-news]
verify_jwt = false
