version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct" # Corrected
      - dependency-type: "production" # Corrected
    versioning-strategy: "auto" # Changed to recommended strategy
    groups:
      production-deps:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      dev-deps:
        dependency-type: "development"
        update-types: ["minor", "patch"]
    reviewers:
      - "zikalyze"
    assignees:
      - "zikalyze"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
